---
title: "R Notebook"
---

```{r, libraries}
library(rstan)
library(bayesplot)
library(tidyverse)
library(tidybayes)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

`%notin%` <- Negate(`%in%`)

```

```{r, prepare_data}
d = read_csv('../data/simulated_data.csv') %>%
  filter(subjectids<=100)


obs_times = seq(0.5, 12, 0.5)
condition = d %>% 
  filter(times %in%obs_times)

no_condition = d %>% 
  filter(times %notin% obs_times)

model_data = list(
  yobs = condition$Cobs,
  subjectids = condition$subjectids,
  n_subjects = length(unique(condition$subjectids)),
  times = condition$times,
  N = nrow(condition),
  #----------pred data---------
  Ntest = nrow(no_condition),
  test_ids = no_condition$subjectids,
  test_times = no_condition$times
)

saveRDS(model_data,'../data/simulated_data_dump.Rdump')

```

```{r, mcmc}

model = stan_model('models/strong_model.stan')

fit = sampling(model,
               readRDS('../data/simulated_data_dump.Rdump'),
               warmup=1000,
               iter=4000,
               chains = 12,
               control = list(adapt_delta=0.8))

p = rstan::extract(fit)

mcmc_pred = apply(p$ypred, 2, mean)

```


```{r, get_estimates}

#MCMC
mcmc_pred = apply(p$ypred, 2, mean)
mcmc_low = apply(p$ypred, 2, function(x) quantile(x, 0.025))
mcmc_high = apply(p$ypred, 2, function(x) quantile(x, 0.975))

predictions = tibble(
  mcmc_pred,
  mcmc_low,
  mcmc_high,
)

predictions %>% 
rename(pred = mcmc_pred, low = mcmc_low, high = mcmc_high) %>% 
bind_cols(no_condition) %>% 
  mutate(type='mcmc') %>% 
  write_csv('../data/mcmc_predictions.csv')

```


```{r}
no_condition %>% 
  bind_cols(predictions) %>% 
  filter(subjectids %in% 1:12) %>% 
  ggplot()+
  geom_line(aes(times, mcmc_pred, color = 'MCMC'))+
  geom_ribbon(aes(times, ymin = mcmc_low, ymax = mcmc_high, fill = 'MCMC'), alpha = 0.25)+
  geom_line(aes(times, C, color = 'Latent Concentration'))+
  facet_wrap(~subjectids, scales = 'free_y')+
  theme(aspect.ratio = 1)+
  labs(x='Time', y='Concentration mg/L', Title='Interval Estimates for concentration')+
  scale_fill_manual(values=c('blue'))+
  scale_color_manual(values=c('red','blue'))+
  labs(fill='Intervals')
```

```{r}
fit %>% 
  spread_draws(mu_CL, n=2000) %>% 
  mean_qi
```

```{r}
param_names = colnames(as.matrix(fit))
m = as.matrix(fit)
mcmc_params = list(
  ke = m[, grepl('ke',param_names)],
  ka = m[, grepl('ka',param_names)],
  cl = m[, grepl('Cl',param_names)]
)

saveRDS(mcmc_params, '../data/mcmc_parameter_draws.RDS')
```


