---
title: "Stan MAP"
---
```{r, libraries}
library(rstan)
library(bayesplot)
library(tidyverse)
library(tidybayes)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

`%notin%` <- Negate(`%in%`)

```

```{r, prepare_data}
d = read_csv('../data/simulated_data.csv') %>%
  filter(subjectids<=100)


obs_times = seq(0.5, 12, 0.5)

condition = d %>% 
  filter(times %in%obs_times)

no_condition = d %>% 
  filter(times %notin% obs_times)

model_data = list(
  yobs = condition$Cobs,
  subjectids = condition$subjectids,
  n_subjects = length(unique(condition$subjectids)),
  times = condition$times,
  N = nrow(condition),
  #----------pred data---------
  Ntest = nrow(no_condition),
  test_ids = no_condition$subjectids,
  test_times = no_condition$times
)

saveRDS(model_data,'../data/simulated_data_dump.Rdump')
```


```{r, MAP}

model_file = 'models/strong_model.stan'
model = stan_model(model_file)
model_data = readRDS('../data/simulated_data_dump.Rdump')

maps = optimizing(
  model,
  data = model_data,
  verbose = TRUE,
  algorithm = 'LBFGS',
  as_vector = TRUE,
  hessian = TRUE,
  tol_obj=1e-10,
  iter=10000,
  draws = 10000
)

H = maps$hessian
S = MASS::ginv(-H)
dimnames(S) = dimnames(H)
theta_tilde = maps$theta_tilde

```


```{r, get_estimates}

#MAP

ypred_cols = theta_tilde[, grepl('ypred', colnames(theta_tilde))]
map_pred = apply(ypred_cols, 2, mean)
map_low = apply(ypred_cols, 2, function(x) quantile(x, 0.025))
map_high = apply(ypred_cols, 2, function(x) quantile(x, 0.975))


predictions = tibble(
  map_pred,
  map_low,
  map_high
)


predictions %>% 
rename(pred = map_pred, low = map_low, high = map_high) %>% 
bind_cols(no_condition) %>% 
  mutate(type='map') %>% 
  write_csv('../data/map_predictions.csv')


```


```{r}



no_condition %>% 
  bind_cols(predictions) %>% 
  filter(subjectids %in% 1:12) %>% 
  ggplot()+
  geom_line(aes(times, map_pred, color = 'MAP'))+
  geom_ribbon(aes(times, ymin = map_low, ymax = map_high, fill = 'MAP'), alpha = 0.25)+
  geom_line(aes(times, C, color = 'Latent Concentration'))+
  facet_wrap(~subjectids, scales = 'free_y')+
  theme(aspect.ratio = 1)+
  labs(x='Time', y='Concentration mg/L', Title='Interval Estimates for concentration')+
  scale_fill_manual(values=c('black'))+
  scale_color_manual(values=c('red','black'))+
  labs(fill='Intervals')
```


```{r}
ka = theta_tilde[,'ka[12]']
ke = theta_tilde[,'ke[12]']
CL = theta_tilde[,'Cl[12]']

pk<-function(ka,ke,CL,t){
  2.5*ke*ka/(CL*(ke-ka))*(exp(-ka*t) - exp(-ke*t))
}

tibble(
  ka,
  ke, 
  CL
) %>% 
  mutate(t = list(seq(0,12,0.5))) %>% 
  mutate(y = pmap(., pk),
         id = 1:n()) %>% 
  unnest(t,y)  %>% 
  group_by(t) %>% 
  tidybayes::mean_qi(y) %>% 
  ggplot()+
  geom_line(aes(t,y))+
  geom_ribbon(aes(t, ymin=.lower, ymax=.upper), alpha = 0.5)+
  theme(aspect.ratio = 1/1.61)
```



```{r}
apply(ypred_cols, 2, function(x) tidybayes::mean_hdci(x)) %>% 
  reduce(bind_rows) %>% 
  bind_cols(no_condition) %>% 
  ggplot()+
  geom_line(aes(times, y, color = 'MAP'))+
  geom_ribbon(aes(times, ymin = ymin, ymax = ymax, fill = 'MAP'), alpha = 0.25)+
  geom_line(aes(times, C, color = 'Latent Concentration'))+
  facet_wrap(~subjectids, scales = 'free_y')+
  theme(aspect.ratio = 1)+
  labs(x='Time', y='Concentration mg/L', Title='Interval Estimates for concentration')+
  scale_fill_manual(values=c('black'))+
  scale_color_manual(values=c('red','black'))+
  labs(fill='Intervals')
```

```{r}

theta_tilde %>% 
  spread_draws(ypred[i], n=500) %>% 
  left_join(no_condition %>% mutate(i = 1:n())) %>%  
  filter(subjectids<21)  %>% 
  ggplot(aes(times, ypred, group = .draw), color = 'red')+
  geom_line( size = 1, alpha = 0.1)+
  facet_wrap(~subjectids, scales = 'free_y')+
  viridis::scale_color_viridis()
```


```{r}
param_draws = list(
  ke = theta_tilde[,grep('ke', colnames(theta_tilde))],
  ka = theta_tilde[,grep('ka', colnames(theta_tilde))],
  cl = theta_tilde[,grep('Cl', colnames(theta_tilde))]
  )

saveRDS(param_draws, '../data/map_parameter_draws.RDS')
  
```


```{r}
subject_params = theta_tilde %>% 
  gather_draws(Cl[subject], ke[subject], ka[subject], alpha[subject], t[subject]) %>% 
  mean_qi()


write_csv(subject_params,'../data/map_patient_parameter_estimates.csv')
```




