---
title: "R Notebook"

---

```{r}
library(tidyverse)
library(ggpubr)
library(Metrics)
theme_set(theme_classic())
files = c('../data/mcmc_predictions.csv', '../data/map_predictions.csv')

d = map(files, read_csv) %>% 
  reduce(bind_rows) %>% 
  mutate(pred = 1000*pred, 
         low = 1000*low,
         high = 1000*high,
         C = 1000*C)
  

subjects =  paste('Subject ', 1:100)

d %>% 
  mutate(type = stringr::str_to_upper(type),
         subject = factor(paste('Subject ', subjectids), ordered = T, levels = subjects)
         ) %>% 
  filter(subjectids<=20) %>% 
  ggplot(aes(times, pred, ymin=low, ymax=high, fill=type))+
  geom_ribbon(alpha = 0.5)+
  facet_wrap(~subject, scales = 'free_y')+
  scale_fill_manual(values = c('red','blue'))+
  theme_classic()+
  theme(legend.position = 'top')+
  labs(x='Time (Hours Post Dose)', y='Concentration ng/mL', fill = 'Method')
  

ggsave('../figs/figure_1.png', height = 5, width = 8)

bad_ones = d %>% 
  filter(between(times, 1, 5)) %>% 
  mutate(width = high - low) %>% 
  select(subjectids, times, width, type) %>% 
  spread(type, width) %>% 
  mutate(r = map/mcmc) %>% 
  group_by(subjectids) %>% 
  filter(r == max(r)) %>% 
  filter(r>=1.5) %>% 
  distinct(subjectids)



d %>% 
  right_join(bad_ones) %>% 
  mutate(type = stringr::str_to_upper(type),
         subject = factor(paste('Subject ', subjectids), ordered = T, levels = subjects)
         ) %>% 
  ggplot(aes(times, pred, ymin=low, ymax=high, fill=type))+
  geom_ribbon(alpha = 0.5)+
  facet_wrap(~subject, scales = 'free_y')+
  scale_fill_manual(values = c('red','blue'))+
  theme_classic()+
  theme(legend.position = 'top', aspect.ratio = 1/1.61)+
  labs(x='Time (Hours Post Dose)', y='Concentration ng/mL', fill = 'Method')
  
  
ggsave('../figs/bad_ones.png', height = 5, width = 8)

```


```{r}
true_v_pred = d %>% 
  mutate(type = stringr::str_to_upper(type)) %>% 
  ggplot(aes(C,pred))+
  geom_point(aes(color=type), alpha = 0.25, size = 1)+
  geom_abline()+
  scale_color_manual(values = c('red','blue'))+
  scale_x_log10()+
  scale_y_log10()+
  theme(aspect.ratio = 1,
        legend.position = 'top')+
  labs(x = 'Latent log(Concentration)', 
       y='Predicted Latent log(Cocentration)', 
       color = 'Method')


compare_mcmc_map = d %>% 
  select(times, subjectids, type, pred) %>% 
  spread(type, pred) %>% 
  ggplot(aes(mcmc, map))+
  geom_point(size = 1, alpha = 0.25)+
  geom_abline()+
  scale_x_log10()+
  scale_y_log10()+
  theme(aspect.ratio = 1)+
  labs(x='MCMC Predicted  log(Concentration)', y='MAP Predicted log(Concentration)')


d %>% 
  select(times, subjectids, type, pred, C) %>% 
  spread(type, pred) %>% 
  mutate(diff = mcmc - map, mn = (mcmc + map)/2) %>% 
  ggplot(aes(mn, diff))+
  geom_point(size = 1, alpha = 0.25)+
  theme(aspect.ratio = 1)+
  labs(x='MCMC Predicted  log(Concentration)', y='MAP Predicted log(Concentration)')

figure <- ggarrange(true_v_pred, compare_mcmc_map,
                    labels = c("A", "B"),
                    ncol = 2, common.legend = T)


figure
ggsave('../figs/compare.png', plot = figure, height = 4)
```

```{r}
preds = d %>% 
  select(times, subjectids, type, pred, C) %>% 
  spread(type, pred)

mcmc_args = rep(list(list(actual = preds$C, predicted = preds$mcmc)), 3)
map_args = rep(list(list(actual = preds$C, predicted = preds$map)), 3)
funcs = list(rmse, mae, mape)
mets = c('RMSE','MAE', "MAPE")


tibble(
  metrics = mets,
  mcmc = invoke_map_dbl(funcs, mcmc_args),
  map = invoke_map_dbl(funcs, map_args)
  ) %>% 
  mutate_if(is.numeric, list(function(x) round(x,2)))
  
```

