---
title: "Run HMC and MAP"
---

```{r libs}
library(bayesplot)
library(here)
library(rstan)
library(tidyverse)
library(tidybayes)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

`%notin%` <- Negate(`%in%`)

```

```{r load_data_and_model}

# Load Simulated data. Only want 100 subjects
data_location = here('analysis','data','simulated_data.csv')
d = read_csv(data_location) %>%
    filter(subjectids<=100)


obs_times = seq(0.5, 12, 0.5)

# Training
condition = d %>% 
  filter(times %in%obs_times)

# Testing
no_condition = d %>% 
  filter(times %notin% obs_times)

model_data = list(
  yobs = condition$Cobs,
  subjectids = condition$subjectids,
  n_subjects = length(unique(condition$subjectids)),
  times = condition$times,
  N = nrow(condition),
  #----------pred data---------
  Ntest = nrow(no_condition),
  test_ids = no_condition$subjectids,
  test_times = no_condition$times
)

saveRDS(model_data, here('analysis','data','simulated_data_dump.Rdump'))


#Load model for HMC and MAP
model_file = here('analysis','models','strong_model.stan')
model = stan_model(model_file)

```

```{r MAP}
# Do MAP
maps = optimizing(
  model,
  data = model_data,
  verbose = TRUE,
  algorithm = 'LBFGS',
  as_vector = TRUE,
  hessian = TRUE,
  tol_obj=1e-10,
  iter=10000,
  draws = 10000
)

H = maps$hessian
S = MASS::ginv(-H)
dimnames(S) = dimnames(H)
theta_tilde = maps$theta_tilde

# Save predictions
ypred_cols = theta_tilde[, grepl('ypred', colnames(theta_tilde))]
map_pred = apply(ypred_cols, 2, mean)
map_low = apply(ypred_cols, 2, function(x) quantile(x, 0.025))
map_high = apply(ypred_cols, 2, function(x) quantile(x, 0.975))
predictions = tibble(map_pred, map_low, map_high)

data_location = here('analysis','data', 'map_predictions.csv')
predictions %>% 
rename(pred = map_pred, low = map_low, high = map_high) %>% 
bind_cols(no_condition) %>% 
  mutate(type='map') %>% 
  write_csv(data_location)


# Save parameters
param_draws = list(
  ke = theta_tilde[,grep('ke', colnames(theta_tilde))],
  ka = theta_tilde[,grep('ka', colnames(theta_tilde))],
  cl = theta_tilde[,grep('Cl', colnames(theta_tilde))]
  )

data_location = here('analysis','data','map_parameter_draws.RDS')
saveRDS(param_draws, data_location)
  

```


```{r map_plot}
#Plot first few patients to see if it worked
no_condition %>% 
  bind_cols(predictions) %>% 
  filter(subjectids %in% 1:12) %>% 
  ggplot()+
  geom_line(aes(times, map_pred, color = 'MAP'))+
  geom_ribbon(aes(times, ymin = map_low, ymax = map_high, fill = 'MAP'), alpha = 0.25)+
  geom_line(aes(times, C, color = 'Latent Concentration'))+
  facet_wrap(~subjectids, scales = 'free_y')+
  theme(aspect.ratio = 1)+
  labs(x='Time', y='Concentration mg/L', Title='Interval Estimates for concentration')+
  scale_fill_manual(values=c('black'))+
  scale_color_manual(values=c('red','black'))+
  labs(fill='Intervals')
```



```{r HMC}
# WARNING: Takes approx 30 mins
fit = sampling(model,
               model_data, 
               warmup=1000,
               iter=4000,
               chains = 12,
               control = list(adapt_delta=0.8))
```


```{r }
p = rstan::extract(fit)

mcmc_pred = apply(p$ypred, 2, mean)

# Make predictions and save to file
mcmc_pred = apply(p$ypred, 2, mean)
mcmc_low = apply(p$ypred, 2, function(x) quantile(x, 0.025))
mcmc_high = apply(p$ypred, 2, function(x) quantile(x, 0.975))

predictions = tibble(mcmc_pred, mcmc_low, mcmc_high)

data_location = here('analysis','data','mcmc_predictions.csv')
predictions %>% 
rename(pred = mcmc_pred, low = mcmc_low, high = mcmc_high) %>% 
bind_cols(no_condition) %>% 
  mutate(type='mcmc') %>% 
  write_csv(data_location)


# Save parameters for later

param_names = colnames(as.matrix(fit))
m = as.matrix(fit)
mcmc_params = list(
  ke = m[, grepl('ke',param_names)],
  ka = m[, grepl('ka',param_names)],
  cl = m[, grepl('Cl',param_names)]
)

data_location = here('analysis','data','mcmc_parameter_draws.RDS')
saveRDS(mcmc_params, data_location)

```

